/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by: npm run photos
 * Generated at: 2025-12-31T04:32:57.466Z
 */

export const photoManifest: Record<string, string[]> = {
  "baltimore": [
    "01.jpg",
    "02.jpg",
    "03.jpg"
  ],
  "cancun": [
    "01.jpg",
    "02.jpg",
    "03.jpg",
    "04.jpg"
  ],
  "munich": [
    "01.jpg",
    "02.jpg",
    "03.jpg",
    "04.jpg",
    "05.jpg",
    "06.jpg",
    "07.jpg",
    "08.jpg"
  ],
  "playa-hermosa": [
    "01.jpg",
    "02.jpg",
    "03.jpg",
    "04.jpg",
    "05.jpg",
    "06.jpg",
    "07.jpg",
    "08.jpg"
  ]
};

export function photosForSlug(slug: string): string[] {
  return photoManifest[slug] ?? [];
}
