/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by: npm run photos
 * Generated at: 2025-12-31T03:14:00.005Z
 */

export const photoManifest: Record<string, string[]> = {
  "cancun": [
    "01.jpg",
    "02.jpg",
    "03.jpg",
    "04.jpg",
    "05.jpg",
    "06.jpg"
  ],
  "munich": [
    "01.jpg",
    "02.jpg",
    "03.jpg",
    "04.jpg",
    "05.jpg",
    "06.jpg",
    "07.jpg",
    "08.jpg"
  ]
};

export function photosForSlug(slug: string): string[] {
  return photoManifest[slug] ?? [];
}
